//--------------------------------------------------------------------------
//  Project      : w11clubm.ide
//  File Name    : w11hdrsm.h
//  Written by   : Ioan Ghip
//  Created      : 15.10.1994
//  Finished     : 26.06.1995
//--------------------------------------------------------------------------
//  Dest. System : windows
//--------------------------------------------------------------------------
//  Libraries    : raima
//--------------------------------------------------------------------------
//  Data Files   :
//--------------------------------------------------------------------------
//  Remarks
//--------------------------------------------------------------------------
//  1994 by FUTURA Software s.r.l.
//--------------------------------------------------------------------------
#include <owl\buttonga.h>
#include <owl\statusba.h>
#include <owl\listbox.h>
#include <owl\edit.h>
#include <owl\preview.h>
#include <owl\controlb.h>
#include <owl\static.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <math.h>
#include <cstring.h>
#include <owl\applicat.h>
#include <owl\dialog.h>
#include <owl\framewin.h>
#include <owl\checkbox.h>
#include <owl\combobox.h>
#include <owl\validate.h>
#include <stdlib.h>  // for atoi
#include <ctype.h>   // for isdigit and isalpha
#include <owl\radiobut.h>
#include <owl\owlpch.h>
#include <owl\dc.h>
#include <owl\vbxctl.h>
#include <owl\textgadg.h>
#include <owl\module.h>
#include <io.h>
#include <fcntl.h>
#include <sys\stat.h>
#include "vbx\include\vtss.h"
#include "vbx\include\tkchart1.h"
#include "vbx\include\vtssonl1.h"
#include "w11print.h"
#include "w11dlgap.rh"
#include "w11dlgap.h"
#include "w11txinp.h"
#include "w04itext.h"
#include "w03inumb.h"
#include "w11globa.h"
#include "w11messg.h"
#include "w11date.h"
#include "w11time.h"
#include "pxfile.h"
#include "clubdat.h"
#include <ver.h>
//--------------------------------------------------------------------------
//  End File : w11hdrsm.h
//--------------------------------------------------------------------------






